### ISSUE TITLE
thanks for your great work,I want to know when will the code release.

### ISSUE THREAD

**Issue by YAwei666** [goodproj13/SG-Net#1]

**Comment by goodproj13** [comment]
Thanks for your interest. We should release the code in couple of weeks, presumably by May 1th.

**Comment by 9p15p** [comment]
Thank you for your great work.
And Today is May Day. 
Looking forward to your great work, Thanks.

**Comment by goodproj13** [comment]
Thanks for your patience. Most of the authors are PhD students and graduating this spring, so they are pretty handful in the recent period. The code will be release very soon once they take care of their school errand.

Thank you!


________________________________

**Comment by whsocool** [comment]
I also want to know when will the code release，thanks！
